//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AluraFlix.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensDeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensDeErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AluraFlix.Exceptions.ResourceMensagensDeErro", typeof(ResourceMensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas o hexadecimal é suportado. ATEANÇÃO coloque a cerquilha (#) no inicio do codigo..
        /// </summary>
        public static string CATEGORIA_COR_INVALIDO {
            get {
                return ResourceManager.GetString("CATEGORIA_COR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Cor deve conter no maximo 15 caracteres.
        /// </summary>
        public static string CATEGORIA_COR_MAXIMO15CARACTERES {
            get {
                return ResourceManager.GetString("CATEGORIA_COR_MAXIMO15CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Cor é obrigatório..
        /// </summary>
        public static string CATEGORIA_COR_VAZIO {
            get {
                return ResourceManager.GetString("CATEGORIA_COR_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria selecionada não existe..
        /// </summary>
        public static string CATEGORIA_INEXISTENTE {
            get {
                return ResourceManager.GetString("CATEGORIA_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Titulo deve conter no maximo 200 caracteres.
        /// </summary>
        public static string CATEGORIA_TITULO_MAXIMO200CARACTERES {
            get {
                return ResourceManager.GetString("CATEGORIA_TITULO_MAXIMO200CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Título é obrigatório..
        /// </summary>
        public static string CATEGORIA_TITULO_VAZIO {
            get {
                return ResourceManager.GetString("CATEGORIA_TITULO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email já existe na nossa base de dados..
        /// </summary>
        public static string EMAIL_EXISTENTE {
            get {
                return ResourceManager.GetString("EMAIL_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email é obrigatório..
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login invalido! verifique o email e senha e tente novamente..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email esta inválido..
        /// </summary>
        public static string USUARIO_EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome deve conter no maximo 200 caracteres.
        /// </summary>
        public static string USUARIO_NOME_MAXIMO200CARACTERES {
            get {
                return ResourceManager.GetString("USUARIO_NOME_MAXIMO200CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório..
        /// </summary>
        public static string USUARIO_NOME_VAZIO {
            get {
                return ResourceManager.GetString("USUARIO_NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo categoriaId é obrigatório..
        /// </summary>
        public static string VIDEO_CATEGORIAID_VAZIO {
            get {
                return ResourceManager.GetString("VIDEO_CATEGORIAID_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Descrição deve conter no maximo 600 caracteres.
        /// </summary>
        public static string VIDEO_DESCRICAO_MAXIMO600CARACTERES {
            get {
                return ResourceManager.GetString("VIDEO_DESCRICAO_MAXIMO600CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Descrição é obrigatório..
        /// </summary>
        public static string VIDEO_DESCRICAO_VAZIO {
            get {
                return ResourceManager.GetString("VIDEO_DESCRICAO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Titulo deve conter no maximo 300 caracteres.
        /// </summary>
        public static string VIDEO_TITULO_MAXIMO300CARACTERES {
            get {
                return ResourceManager.GetString("VIDEO_TITULO_MAXIMO300CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Titulo é obrigatório..
        /// </summary>
        public static string VIDEO_TITULO_VAZIO {
            get {
                return ResourceManager.GetString("VIDEO_TITULO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O URL é inválido..
        /// </summary>
        public static string VIDEO_URL_INVALIDO {
            get {
                return ResourceManager.GetString("VIDEO_URL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo URL é obrigatório..
        /// </summary>
        public static string VIDEO_URL_VAZIO {
            get {
                return ResourceManager.GetString("VIDEO_URL_VAZIO", resourceCulture);
            }
        }
    }
}
